export const MOVIE_POPULAR_REQUEST = 'MOVIE_POPULAR_REQUEST';
export const MOVIE_POPULAR_SUCCESS = 'MOVIE_POPULAR_SUCCESS';
export const MOVIE_POPULAR_FAIL = 'MOVIE_POPULAR_FAIL';

export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAIL = 'MOVIE_SEARCH_FAIL';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
